import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1788454689642 implements MigrationInterface {
    name = 'InitialSchema1788454689642'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Not generated by the CLI, which only diffs tables: every "id" below
        // defaults to uuid_generate_v4() and gtfs_stop.location is a PostGIS
        // geometry, so both extensions must exist before the first CREATE
        // TABLE. A managed host that pre-installs them makes these no-ops.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS postgis`);
        await queryRunner.query(`CREATE TABLE "mobility_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "preferredModes" jsonb NOT NULL, "favoriteAddresses" jsonb NOT NULL, "pmrAccessibility" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_57177823171a9779e1be8c46055" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "mobilityProfileId" uuid, CONSTRAINT "UQ_3fa909d0e37c531ebc237703391" UNIQUE ("email"), CONSTRAINT "REL_a6c20185a769b322f0570b65af" UNIQUE ("mobilityProfileId"), CONSTRAINT "PK_22a5c4a3d9b2fb8e4e73fc4ada1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_journey_segment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "journeyDbId" uuid NOT NULL, "order" integer NOT NULL, "mode" character varying NOT NULL, "durationSeconds" integer NOT NULL, "distanceMeters" double precision NOT NULL DEFAULT '0', "carbonGrams" double precision NOT NULL, "fromName" character varying NOT NULL, "fromLat" double precision NOT NULL, "fromLon" double precision NOT NULL, "toName" character varying NOT NULL, "toLat" double precision NOT NULL, "toLon" double precision NOT NULL, CONSTRAINT "PK_655c135f0a5b669a63c32a0543b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "saved_journey" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userDbId" uuid NOT NULL, "durationSeconds" integer NOT NULL, "carbonGrams" double precision NOT NULL, "degraded" boolean NOT NULL DEFAULT false, "savedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1100d98795c289003789a0b8e5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gtfs_agency" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agencyId" character varying NOT NULL, "agencyName" character varying NOT NULL, "agencyUrl" character varying NOT NULL, "agencyTimezone" character varying NOT NULL, "agencyLang" character varying, "agencyPhone" character varying, CONSTRAINT "UQ_ae7bd5f386bcdce2e94a4c65edf" UNIQUE ("agencyId"), CONSTRAINT "PK_b40dba94c77637eea5f24240e47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gtfs_route" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "routeId" character varying NOT NULL, "agencyDbId" uuid NOT NULL, "routeShortName" character varying, "routeLongName" character varying, "routeType" integer NOT NULL, "routeColor" character varying, "routeTextColor" character varying, CONSTRAINT "UQ_6615a0e1bba8d53729ecd693f6a" UNIQUE ("routeId"), CONSTRAINT "PK_768ccbde0dd15790db65b82fb83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gtfs_calendar" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "serviceId" character varying NOT NULL, "monday" boolean NOT NULL, "tuesday" boolean NOT NULL, "wednesday" boolean NOT NULL, "thursday" boolean NOT NULL, "friday" boolean NOT NULL, "saturday" boolean NOT NULL, "sunday" boolean NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, CONSTRAINT "UQ_85288dc15a67679c3a8882ff65b" UNIQUE ("serviceId"), CONSTRAINT "PK_548f149cb5b5ab1f44a4d905feb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gtfs_trip" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripId" character varying NOT NULL, "routeDbId" uuid NOT NULL, "calendarDbId" uuid NOT NULL, "tripHeadsign" character varying, CONSTRAINT "UQ_385ec4eeb1a792d415307a9d850" UNIQUE ("tripId"), CONSTRAINT "PK_8899eff9825ba71ae6eac646070" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gtfs_stop" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stopId" character varying NOT NULL, "stopCode" character varying, "stopName" character varying NOT NULL, "location" geometry(Point,4326) NOT NULL, "parentStation" character varying, CONSTRAINT "UQ_31f786cb2576942f7f1462c26b9" UNIQUE ("stopId"), CONSTRAINT "PK_d633d8ce230c2e7eb37d371d502" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d5212e24b81e4d35d0e15b15a1" ON "gtfs_stop" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "gtfs_stop_time" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tripDbId" uuid NOT NULL, "stopDbId" uuid NOT NULL, "arrivalTime" character varying NOT NULL, "departureTime" character varying NOT NULL, "stopSequence" integer NOT NULL, CONSTRAINT "UQ_95544847dee18ab23b057d84ea2" UNIQUE ("tripDbId", "stopDbId", "stopSequence"), CONSTRAINT "PK_dd7edd37c7d035ff68e59430b38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD CONSTRAINT "FK_a6c20185a769b322f0570b65afd" FOREIGN KEY ("mobilityProfileId") REFERENCES "mobility_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_journey_segment" ADD CONSTRAINT "FK_0f6c1b0e6ae78f6c8e1a918cc66" FOREIGN KEY ("journeyDbId") REFERENCES "saved_journey"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_journey" ADD CONSTRAINT "FK_0f98a2a0a8a5f6139a7fd529b82" FOREIGN KEY ("userDbId") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gtfs_route" ADD CONSTRAINT "FK_e3fa547e88e653b9212a6097f63" FOREIGN KEY ("agencyDbId") REFERENCES "gtfs_agency"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gtfs_trip" ADD CONSTRAINT "FK_1eb3f46ed13fffa1b77176661e3" FOREIGN KEY ("routeDbId") REFERENCES "gtfs_route"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gtfs_trip" ADD CONSTRAINT "FK_1cab70a302ca83886402a5904be" FOREIGN KEY ("calendarDbId") REFERENCES "gtfs_calendar"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gtfs_stop_time" ADD CONSTRAINT "FK_337722077d2b5bbd1354ab06067" FOREIGN KEY ("tripDbId") REFERENCES "gtfs_trip"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gtfs_stop_time" ADD CONSTRAINT "FK_3c684b75d877afdcb981285aa60" FOREIGN KEY ("stopDbId") REFERENCES "gtfs_stop"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "gtfs_stop_time" DROP CONSTRAINT "FK_3c684b75d877afdcb981285aa60"`);
        await queryRunner.query(`ALTER TABLE "gtfs_stop_time" DROP CONSTRAINT "FK_337722077d2b5bbd1354ab06067"`);
        await queryRunner.query(`ALTER TABLE "gtfs_trip" DROP CONSTRAINT "FK_1cab70a302ca83886402a5904be"`);
        await queryRunner.query(`ALTER TABLE "gtfs_trip" DROP CONSTRAINT "FK_1eb3f46ed13fffa1b77176661e3"`);
        await queryRunner.query(`ALTER TABLE "gtfs_route" DROP CONSTRAINT "FK_e3fa547e88e653b9212a6097f63"`);
        await queryRunner.query(`ALTER TABLE "saved_journey" DROP CONSTRAINT "FK_0f98a2a0a8a5f6139a7fd529b82"`);
        await queryRunner.query(`ALTER TABLE "saved_journey_segment" DROP CONSTRAINT "FK_0f6c1b0e6ae78f6c8e1a918cc66"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP CONSTRAINT "FK_a6c20185a769b322f0570b65afd"`);
        await queryRunner.query(`DROP TABLE "gtfs_stop_time"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5212e24b81e4d35d0e15b15a1"`);
        await queryRunner.query(`DROP TABLE "gtfs_stop"`);
        await queryRunner.query(`DROP TABLE "gtfs_trip"`);
        await queryRunner.query(`DROP TABLE "gtfs_calendar"`);
        await queryRunner.query(`DROP TABLE "gtfs_route"`);
        await queryRunner.query(`DROP TABLE "gtfs_agency"`);
        await queryRunner.query(`DROP TABLE "saved_journey"`);
        await queryRunner.query(`DROP TABLE "saved_journey_segment"`);
        await queryRunner.query(`DROP TABLE "app_user"`);
        await queryRunner.query(`DROP TABLE "mobility_profile"`);
        // The extensions are deliberately left installed: they are
        // database-wide, and another schema in the same database may rely on
        // them. Dropping them here would reach outside this migration's scope.
    }

}
